#!/bin/sh

### BEGIN INIT INFO
# Provides:          fastcgi-wrapper.pl
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: starts fastcgi-wrapper.pl
### END INIT INFO

set -u

DAEMON="FASTCGI WRAPPER"
FCGI_CMD=/usr/bin/fastcgi-wrapper.pl
FCGI_PID=/var/run/fastcgi-wrapper.pid
TIMEOUT=30

FCGI_OPTIONS=""
SSD_OPTIONS="--oknodo --quiet --pidfile $FCGI_PID --exec $FCGI_CMD"

. /lib/lsb/init-functions

case "$1" in
    start)
	log_begin_msg "Starting $DAEMON..."

	/sbin/start-stop-daemon --start $SSD_OPTIONS -- $FCGI_OPTIONS
	log_end_msg $?
    ;;
    stop)
	log_begin_msg "Stopping $DAEMON..."

	/sbin/start-stop-daemon --stop $SSD_OPTIONS
	log_end_msg $?
    ;;
    graceful-stop)
	log_begin_msg "Gracefully stopping $DAEMON..."

	/sbin/start-stop-daemon --stop --retry QUIT/$TIMEOUT/TERM $SSD_OPTIONS
	log_end_msg $?
    ;;
    restart)
	$0 stop
	$0 start
    ;;
    *)
	echo "Usage: $0 {start|stop|graceful-stop|restart}"
	exit 1
    ;;
esac
